### ISSUE TITLE
No root route in routes.rb

### ISSUE THREAD

**Issue by pferdefleisch** [refugeeHackVienna/iamin#1]
Just add one

**Comment by klappradla** [comment]
There is one: see [here](https://github.com/refugeeHackVienna/iamin/blob/master/config/routes.rb#L5 )

It simply points to devise' login screen for now.

**Comment by pferdefleisch** [comment]
The way it sounded, we didn't require people to log in. I thought we would have a landing page and whatnot. So maybe that is the actual issue... Feature: Landing Page

**Comment by klappradla** [comment]
Got u. I'll throw a bootstrapped one in. Maybe even tonight if I'm done with work stuff early enough.
