### ISSUE TITLE
NGO Registration

### ISSUE THREAD

**Issue by klappradla** [refugeeHackVienna/iamin#2]
Current workflow to register as NGO:
  1. register as normal user
  2. contact admin, verify as NGO
  3. have admin change ur user-role to 'ngo_admin'

Problems I see:
* hard for admins to keep track on NGO-requests when more (normal) users registering
* NGO requests need to be verified / checked (to not have app trolled by idiots)
* NGOs don't get the registration process without knowing/contacting an admin

Solution I'd propose: **separate registration process for NGOs** (as intended with 2nd button on landing page)

* workflow:
    * NGOs register as NGO-user right away
    * account blocked, notice that account need to be verified
    * admins get mail on new NGO request (can verify email, phone)
    * admin approves request -> email to NGO, account open
* technical
   * additional routes, extend/derive registration controller (minimal effort)
   * eventually STI on user model

Love to 👂 ur feedback on that. Could work on it tomorrow on the train.

**Comment by haslinger** [comment]
Sounds cool, but I'm not sure, how you get Devise to handle both cases in the registrations controller ...

**Comment by klappradla** [comment]
It's possible to derive a 2nd one and extend it with additional functionalities. I think we do not really need another type of user model though - just one column more for the confirmation - all users should be able to handle this 😉

I'll give it a try tomorrow if I manage to stay awake.

**Comment by haslinger** [comment]
Great. +1
